name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main   # รัน workflow เมื่อ push ไป branch main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: .   # deploy ไฟล์ทั้งหมดใน repo

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
